# current server on port ， it port can not to mapping any host
port = 9567

#  authentication https suffixes, the fomart is http://host:port/{authentication}
authentication = "/dmz_locker_demo?hello=world&hello2=world2"

# how invalidate time when authetication
session_time_sec = 86400


# mapping host port

[[mappings]]
port = 8888
addr = "127.0.0.1:8888"
is_public = false
