# current server on port ， it port can not to mapping any host
port = 9000

#  authentication https suffixes, the fomart is http://host:port/{authentication}
authentication = "/ansjsun"

# how invalidate time when authetication
session_time_sec = 86400


# mapping host port


[[mappings]]
port = 3389
addr = "192.168.10.220:3389"
is_public = false

[[mappings]]
port = 2222
addr = "192.168.10.210:22"
is_public = false


[[mappings]]
port = 5000
addr = "192.168.10.205:5000"
is_public = false

[[mappings]]
port = 5001
addr = "192.168.10.205:5001"
is_public = false

[[mappings]]
port = 8096
addr = "192.168.10.205:8096"
is_public = false